POST http://localhost:4000/add
Content-Type: application/json

{
    "text": "buy bread"
}

###

GET http://localhost:4000/todos

###

DELETE http://localhost:4000/deleteTodo/0.1739439743982385

###

POST http://localhost:4000/toggleTodo/0.1739439743982385